"use client";

import { useMemo, useState } from "react";
import {
  calculateJobFitScore,
  defaultManualScores,
  scoringCriteria,
  type ManualScoreInputs,
  type ScoringCriterionId
} from "@/lib/scoring";

const scoreOptions = Array.from({ length: 11 }, (_, value) => value);

type ManualFitScoringProps = {
  currentFitScore?: number;
};

export function ManualFitScoring({ currentFitScore }: ManualFitScoringProps) {
  const [scores, setScores] = useState<ManualScoreInputs>(defaultManualScores);
  const result = useMemo(() => calculateJobFitScore(scores), [scores]);

  function updateScore(criterionId: ScoringCriterionId, value: string) {
    setScores((current) => ({
      ...current,
      [criterionId]: Number(value)
    }));
  }

  return (
    <div className="space-y-5">
      <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
        <p className="text-sm font-semibold text-slate-950">
          Manual scoring only
        </p>
        <p className="mt-1 text-sm leading-6 text-slate-600">
          These scores are selected by the user. They are not generated by AI and
          are not saved to a database yet.
        </p>
      </div>

      <div className="grid gap-4 lg:grid-cols-[1fr_18rem]">
        <div className="grid gap-3">
          {scoringCriteria.map((criterion) => (
            <label
              key={criterion.id}
              className="grid gap-3 rounded-md border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_7rem] sm:items-center"
            >
              <span>
                <span className="block font-medium text-slate-950">
                  {criterion.label}
                </span>
                <span className="mt-1 block text-sm leading-6 text-slate-600">
                  {criterion.description}
                </span>
              </span>
              <select
                className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950 outline-none transition focus:border-slate-500 focus:ring-2 focus:ring-slate-200"
                value={scores[criterion.id]}
                onChange={(event) =>
                  updateScore(criterion.id, event.target.value)
                }
              >
                {scoreOptions.map((score) => (
                  <option key={score} value={score}>
                    {score}/10
                  </option>
                ))}
              </select>
            </label>
          ))}
        </div>

        <aside className="h-fit rounded-lg border border-slate-200 bg-white p-5">
          <p className="text-sm font-medium text-slate-500">
            Calculated manual score
          </p>
          <p className="mt-2 text-4xl font-semibold text-slate-950">
            {result.overallScore}
          </p>
          <p className="mt-1 text-sm text-slate-500">out of 100</p>

          <div className="mt-5 space-y-4 text-sm">
            <div>
              <p className="font-medium text-slate-500">Tier</p>
              <p className="mt-1 font-semibold text-slate-950">
                {result.tier}
              </p>
            </div>
            <div>
              <p className="font-medium text-slate-500">Recommended action</p>
              <p className="mt-1 leading-6 text-slate-700">
                {result.recommendedAction}
              </p>
            </div>
            <div>
              <p className="font-medium text-slate-500">Mock saved score</p>
              <p className="mt-1 text-slate-950">
                {currentFitScore ? `${currentFitScore}/100` : "Not scored yet"}
              </p>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
